includes = ["*.dfy"]
excludes = ["dahlia-remainder.dfy", "K2.dfy", "MIN.dfy"]

[options]
verify-included-files=true
#dont-verify-dependencies=true
verification-time-limit=20
cores=8
isolate-assertions=true
#filter-symbol="xyzzy"
