includes = ["*.dfy"]
# excludes = ["dahlia-remainder.dfy"]
excludes = ["dahlia-remainder.dfy","main.dfy", "Klon.dfy", "Printing.dfy"]

[options]
verify-included-files=true
verification-time-limit=20
cores=8 
isolate-assertions=true
filter-symbol="xyzzy"