includes = ["*.dfy"]
# excludes = ["dahlia-remainder.dfy", "Main.dfy"]
excludes = ["dahlia-remainder.dfy", "Printing.dfy", "Klon.dfy"]

[options]
verify-included-files=true
verification-time-limit=20
cores=8 
isolate-assertions=true
# filter-symbol="xyzzy"

